const url=window.KANASU_SUPABASE_URL,key=window.KANASU_SUPABASE_ANON_KEY;
const configured=url&&!url.includes('YOUR_')&&key&&!key.includes('YOUR_'); const db=configured?window.supabase.createClient(url,key):null;
const $=id=>document.getElementById(id); const msg=(id,t)=>$(id).textContent=t;
let collections=[],slides=[];
function need(){if(!db){alert('Configure supabase-config.js first.');return false}return true}
async function init(){if(!configured){$('setup').classList.remove('hidden');return}
 const {data:{session}}=await db.auth.getSession(); session?showApp():showLogin();
 db.auth.onAuthStateChange((_e,s)=>s?showApp():showLogin());
}
function showLogin(){$('login').classList.remove('hidden');$('dashboard').classList.add('hidden');$('logout').classList.add('hidden')}
async function showApp(){$('login').classList.add('hidden');$('dashboard').classList.remove('hidden');$('logout').classList.remove('hidden');await loadAll()}
$('loginForm').onsubmit=async e=>{e.preventDefault();if(!need())return;const {error}=await db.auth.signInWithPassword({email:$('email').value,password:$('password').value});msg('loginMsg',error?error.message:'Signed in.')};
$('logout').onclick=()=>db.auth.signOut();
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('[id^="tab-"]').forEach(x=>x.classList.add('hidden'));$('tab-'+b.dataset.tab).classList.remove('hidden')});
async function loadAll(){const [s,c,h]=await Promise.all([db.from('site_settings').select('*'),db.from('collections').select('*').order('sort_order'),db.from('hero_slides').select('*').order('sort_order')]); if(s.error) return alert(s.error.message); const m={};s.data.forEach(x=>m[x.key]=x.value); for(const k of ['brand_name','tagline','intro','story_title','story_text'])$(k).value=m[k]||'';$('email_setting').value=m.email||''; collections=c.data||[];slides=h.data||[];renderCollections();renderSlides()}
$('settingsForm').onsubmit=async e=>{e.preventDefault();const rows=['brand_name','tagline','intro','story_title','story_text','email'].map(k=>({key:k,value:k==='email'?$('email_setting').value:$(k).value}));const {error}=await db.from('site_settings').upsert(rows);msg('settingsStatus',error?error.message:'Saved. Refresh the public site to see the changes.')}
function renderCollections(){$('collectionList').innerHTML=collections.map(c=>`<div class="item"><img src="${c.image_url||'assets/kanasu-logo.png'}"><div><strong>${esc(c.name)}</strong><p>${esc(c.description||'')}</p></div><div class="item-actions"><button onclick="editCollection('${c.id}')">Edit</button><button class="danger" onclick="deleteCollection('${c.id}')">Delete</button></div></div>`).join('')||'<p>No collections yet.</p>'}
function renderSlides(){$('heroList').innerHTML=slides.map(h=>`<div class="item"><img src="${h.image_url||'assets/hero-model.jpg'}"><div><strong>${esc(h.title)}</strong><p>${esc(h.description||'')}</p></div><div class="item-actions"><button onclick="editHero('${h.id}')">Edit</button><button class="danger" onclick="deleteHero('${h.id}')">Delete</button></div></div>`).join('')||'<p>No hero slides yet.</p>'}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
$('newCollection').onclick=()=>editCollection();
$('newHero').onclick=()=>editHero();
async function editCollection(id){const c=collections.find(x=>x.id===id)||{name:'',description:'',image_url:'',sort_order:collections.length,published:true};const name=prompt('Collection name:',c.name);if(name===null)return;const description=prompt('Description:',c.description||'');if(description===null)return;const image_url=prompt('Image URL (or Supabase Storage public URL):',c.image_url||'');if(image_url===null)return;const payload={name,description,image_url,sort_order:Number(c.sort_order||0),published:true};const q=id?db.from('collections').update(payload).eq('id',id):db.from('collections').insert(payload);const {error}=await q;if(error)alert(error.message);else loadAll()}
async function deleteCollection(id){if(!confirm('Delete this collection?'))return;const {error}=await db.from('collections').delete().eq('id',id);if(error)alert(error.message);else loadAll()}
async function editHero(id){const h=slides.find(x=>x.id===id)||{eyebrow:'Kanasu Sarees',title:'Timeless Weaves. Rooted in Tradition.',description:'Discover sarees shaped by heritage, artisan skill and a love for beautiful drapes.',image_url:'assets/hero-model.jpg',sort_order:slides.length,published:true};const eyebrow=prompt('Eyebrow:',h.eyebrow||'');if(eyebrow===null)return;const title=prompt('Hero title:',h.title);if(title===null)return;const description=prompt('Description:',h.description||'');if(description===null)return;const image_url=prompt('Image URL:',h.image_url||'');if(image_url===null)return;const payload={eyebrow,title,description,image_url,sort_order:Number(h.sort_order||0),published:true};const q=id?db.from('hero_slides').update(payload).eq('id',id):db.from('hero_slides').insert(payload);const {error}=await q;if(error)alert(error.message);else loadAll()}
async function deleteHero(id){if(!confirm('Delete this hero slide?'))return;const {error}=await db.from('hero_slides').delete().eq('id',id);if(error)alert(error.message);else loadAll()}
init();
